apiVersion: v1
kind: Service
metadata:
  name: rails-deployment
spec:
  type: LoadBalancer
  selector:
    app: rails
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
      name: http

